version: "2017-09-20"
pipeline:
  - id: "build"
    type: script
    commands:
      - desc: "Install dependencies"
        cmd: |
          apt-get update
          apt-get install -q -y --no-install-recommends \
            python3.5 \
            python3.5-dev \
            python3-pip \
            python3-setuptools \
            python3-wheel \
            gcc \
            libffi-dev \
            libssl-dev \
            tox

      - desc: "Run tox"
        cmd: tox

      - desc: "Push Docker Image"
        cmd: |
          IS_PR_BUILD=${CDP_PULL_REQUEST_NUMBER+"true"}
          if [[ ${IS_PR_BUILD} != "true" ]]
          then
            AGENT_IMAGE=registry-write.opensource.zalan.do/logging/kubernetes-log-watcher:${CDP_BUILD_VERSION}
          else
            AGENT_IMAGE=registry-write.opensource.zalan.do/logging/kubernetes-log-watcher-unstable:${CDP_BUILD_VERSION}
          fi
          docker build --tag "$AGENT_IMAGE" .
          docker push "$AGENT_IMAGE"
